version: '3.8'

services:
  # Development Backend with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      LOG_RESPONSE_BODY: "true"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    command: ["npm", "run", "dev"]

  # Development Frontend with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
